// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Infrastructure.Data;

#nullable disable

namespace QuanLyKho.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("QuanLyKho.Domain.Entities.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "",
                            DienThoai = "",
                            Email = "",
                            LogoPath = "",
                            MaSoThue = "",
                            TenCongTy = ""
                        });
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChietKhau")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DienThoaiKH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueGTGT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienDaThu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienSauCK")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTienTruocCK")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueGTGT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienHangChuaThue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienThueGTGT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongCanhBao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiGiaoDich")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.WithholdingTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThuNhapChiuThue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThueKhauTru")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WithholdingTaxes");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("QuanLyKho.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("QuanLyKho.Domain.Entities.Invoice", "Invoice")
                        .WithMany("ChiTiet")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("QuanLyKho.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QuanLyKho.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("ChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
